" Leader key
let mapleader = ";"

if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
  " Copy to the clipboard when yankin
  set clipboard=unnamed
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
"
" If the encoding is not set early then some characters
" like the one used in showbreak look weird
set encoding=utf-8
set backspace=start,eol,indent " Backpsace everywhere in insert mode
set tabstop      =2
set softtabstop  =2
set shiftwidth   =2
set expandtab
set number
set nobackup
set nowritebackup
set backupdir    =~/.vim_backup
set directory    =~/.vim_backup
set laststatus   =2
set hlsearch
set incsearch
set ignorecase
set smartcase
set equalalways
set list
set listchars-=eol:$
set listchars+=tab:..
set listchars+=trail:.
set showbreak=↪
set cursorline
set scrolloff    =10
set wildmenu
set wildmode=list:longest
set whichwrap+=<,>,h,l,[,] "http://vim.wikia.com/wiki/Automatically_wrap_left_and_right
set exrc " Execute commands in per-project .vimrc files
set completeopt=menuone "By default set to preview,menuone but this is annoying if using YouCompleteMe [1]
set cole=1 " Required by vim-javascript to apply its substitutions to keywords

" Reduce timeout after <ESC> is recvd. This is only a good idea on fast links.
" Got at: https://code.google.com/p/iterm2/issues/detail?id=1322
set ttimeout
set ttimeoutlen=20
set notimeout

call plug#begin('~/.vim/vim-plug-installs')

source ~/.vim/vim-plugs
call plug#end()
" Need to make the call to deoplete#custom#source here
" since the runtimepaths are only updated after the call
" to plug#end. If I move the deoplete call together with
" the plugin configuration I would get the following error
"
" Unknown function: deoplete#custom#source
call deoplete#custom#source('ale', 'rank', 999)

filetype plugin indent on
syntax enable
color nova
"hack to make diminactive looks nice when using molokai
hi ColorColumn ctermbg=237

" Load all the other files
source ~/.vim/vim-mappings
source ~/.vim/vim-helpers
source ~/.vim/vim-autocommands

" [1] https://github.com/Valloric/YouCompleteMe#the-gycm_add_preview_to_completeopt-option
